spring:
    datasource:
        url: jdbc:mysql://localhost:3306/demo-spring-boot?useSSL=false
        username: root
        password: password
        driver-class-name: com.mysql.jdbc.Driver
        dbcp2:
            min-idle: 8
            max-idle: 8
            max-total: 10
            initial-size: 5
            max-wait-millis: 10000
    jpa:
      show-sql: false

server:
    port: 8090
    jetty:
        acceptors: 1
        selectors: 2
        accesslog:
            enabled: true
            filename: demo
            retention-period: 10
            append: true
    servlet:
        context-path: /baeldung
